version: '3'
services:
#  backend:
#    build: backend/.
#    environment:
#      - PORT=3000
#      - NODE_ENV=dev
#      - ENV_NAME=local
#    image: tttvlw-backend
#    container_name: tttvlw-backend

  proxy-server:
    build: nginx/.
    ports:
      - 80:80
    restart: always
    image: tttvlw-proxy-server
    container_name: tttvlw-proxy-server
